server:
  port: 8701
spring:
  application:
    name: zuul-8701

eureka:
  instance:
    hostname: client
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      zone: zone1
  server:
    hostname-server1: server1
    server1-port1: 8601
    hostname-server2: server2
    server2-port2: 8602
    hostname-server3: server2
    server3-port3: 8602
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    prefer-same-zone-eureka: true
    region: region-east
    availability-zones:
      region-east: zone1,zone2,zone3
    service-url:
      zone1: http://${eureka.server.hostname-server1}:${eureka.server.server1-port1}/eureka/
      zone2: http://${eureka.server.hostname-server2}:${eureka.server.server2-port2}/eureka/
      zone3: http://${eureka.server.hostname-server3}:${eureka.server.server3-port3}/eureka/

zuul:
  routes:
    service-8081:
      path: /service-8081/**
      serviceId: service-8081
    service-8082:
      path: /service-8082/**
      serviceId: service-8082
  retryable: true

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 15000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000
          strategy: SEMAPHORE
