server:
  port: 8602
spring:
  application:
    name: eureka-server-8602
eureka:
  instance:
    hostname-server1: server1
    hostname-server2: server2
    hostname-server3: server3
    server1-port: 8601
    server2-port: 8602
    server3-port: 8603
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      zone: zone2
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-east
    service-url:
      zone1: http://${eureka.instance.hostname-server1}:${eureka.instance.server1-port}/eureka/
      zone2: http://${eureka.instance.hostname-server2}:${eureka.instance.server2-port}/eureka/
      zone3: http://${eureka.instance.hostname-server3}:${eureka.instance.server3-port}/eureka/
    availability-zones:
      region-east: zone1,zone2,zone3
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    renewal-percent-threshold: 0.9
    response-cache-update-interval-ms: 3000
